// Writes the kernel's WebAssembly into src/kernel-wasm.ts as base64, so Node, the studio's
// bundle and its AudioWorklet all get it from an ordinary import, with no bundler setup.
// Usage: node scripts/embed-wasm.mjs <path to .wasm>
import { readFileSync, writeFileSync } from "node:fs";

const wasm = readFileSync(process.argv[2]);
const lines = wasm.toString("base64").match(/.{1,100}/g);
writeFileSync(
  new URL("../src/kernel-wasm.ts", import.meta.url),
  `// Generated by \`npm run build:wasm -w @synaptix/dsp-kernel\` from crates/wasm-bindings; do not edit.\n` +
    `// CI rebuilds it and fails if it differs.\n` +
    `export const KERNEL_WASM_BASE64 =\n${lines.map((line) => `  "${line}"`).join(" +\n")};\n`
);
